on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC authentications    

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Adjust if you need a different version of Node.js

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the React app
    - name: Build React app
      run: |
          npm run build
          ls 
   # Install AWS CLI v2
    - name: Install AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update 

    # Verify AWS CLI installation
    - name: Verify AWS CLI installation
      run: aws --version

    # Set the bucket folder based on the branch and store it in a variable
    - name: Set bucket name based on branch
      id: set-bucket-name
      run: |
          echo "CLOUDFRONT_DISTRIBUTION_ID=E3S9AOX6IKMVSE" >> $GITHUB_ENV
          echo "BUCKET_NAME=kvs-admin-front-end" >> $GITHUB_ENV
        
    # Configure AWS credentials using OIDC

    - name: Set up AWS credentials using OIDC for Main
      if: github.ref == 'refs/heads/main'  # Runs only for main branch
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: "arn:aws:iam::061039788018:role/github-actions-role-admin"  # Update with your IAM role ARN
        aws-region: "ap-south-1"
    
  
    # Deploy the app to the selected S3 bucket and folder
    - name: Deploy to S3
      run: aws s3 sync ./dist/ s3://$BUCKET_NAME --delete

    # Invalidate CloudFront Cache
    - name: Invalidate CloudFront Cache
      run: |
        DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID  # Replace with your CloudFront distribution ID
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

 
